### ISSUE TITLE
v1 Roadmap

### ISSUE THREAD

**Issue by dai-shi** [dai-shi/wakuwork#24]
Here are tasks that I would like to finish before v1.

- [ ] Server bundling #21 
- [ ] RSC-only SSR (or opt-in SSR)
- [ ] New API as middleware #23
- [ ] Explore RSC-only forms (optional?)
- [ ] Explore running RSCs on client (optional?)

**Comment by Aslemammad** [comment]
How about wakuwork actions? I was thinking about developing a plugin for vite a while ago, Since I think it's something similar to telefunc while developing this tool with Rom Brillout.

**Comment by dai-shi** [comment]
Actions (what I call "React Server Functions") are already implemented. I wouldn't say it's complete though.

**Comment by Aslemammad** [comment]
Nice!

**Comment by EasonYou** [comment]
I found that router ssr doesn't work at present, is that any plane to do it?
(dig into the code, seems like some thing wrong with ``getComponent`` in ``getSsrConfig``, but I have no idea why)

**Comment by tom-sherman** [comment]
Anecdotally there seems to be a fairly large gap between waku's server actions and Next.js' implementation - I suppose this is expected because server actions are completely experimental in React right now.

IMO it makes sense to mark them as such (as an opt-in config option) before releasing v1.

**Comment by dai-shi** [comment]
I don't think our RSF (react server function) isn't that experimental, meaning it's the same level as react server component. I suppose Next's server action does more experimental things.

That said, I would like to revisit our approach anyway, which will require some feedbacks from collaborators/contributors/users.

In any case, unless we have an official doc or RFC from React, we wouldn't be able to finalize our API, which means v1 probably won't land until then.

**Comment by tom-sherman** [comment]
The problem with shipping server actions now (or before they're stable in React) is that the semantics are not specified yet. For example Next.js server actions are queued, it's impossible to execute them concurrently - not the case in Waku. There is also the integration with transitions, not sure if this is implemented in Waku.

IMO need to wait for a React RFC.

**Comment by dai-shi** [comment]
Yeah, if we would release v1 before the callserver RFC, we should hide it behind a flag. For now, just noting it's not finalized would be enough. But in that sense, everything isn't finalized.

**Comment by childrentime** [comment]
@dai-shi How about SSG? And change docs website to static files.

**Comment by dai-shi** [comment]
docs website is already static files.
we generate static files on build (SSG is a vague word, as people expect to generate HTML files.)

**Comment by dai-shi** [comment]
> IMO it makes sense to mark them as such (as an opt-in config option) before releasing v1.

Having been working on #124, I'm getting more skeptical about the stability.
My gut feeling is that we should wait releasing v1 before React 18.3.0 or 19 is out.

**Comment by zouhangwithsweet** [comment]
So waku will not use `react-server-dom-vite` in the future?

**Comment by dai-shi** [comment]
It depends on what `react-server-dom-vite` and `react-server-dom-esm` will be like.

Hope the esm one is published: https://github.com/facebook/react/issues/27197

**Comment by ojj1123** [comment]
>  Integrate React Float

What is React Float? What's the relation with `no index.html`?

**Comment by dai-shi** [comment]
> > Integrate React Float
> 
> @dai-shi What is React Float? What's the relation with `no index.html`?

I hope React docs will cover that soon. It will be called something like hoistable resource/elements.
It's technically not "integration". As #289 may tell, we no longer use `index.html` and add `<title>...</title>` in components, for example, which is possible because of hoistable elements.

**Comment by ojj1123** [comment]
I was wondering if you could explain where it is the explanation of `defineEntries` function in [Docs](https://waku.gg/) or [README](https://github.com/dai-shi/waku)! Is it deprecated?

**Comment by himself65** [comment]
> I was wondering if you could explain where it is the explanation of `defineEntries` function in [Docs](https://waku.gg/) or [README](https://github.com/dai-shi/waku)! I couldn't find it since `waku` was released as `v0.19.0`. Is it deprecated?

No, that API is still available, but we don't have enough documents for the public APIs.

https://waku.gg/blog/introducing-waku

**Comment by dai-shi** [comment]
https://github.com/dai-shi/waku/issues/24#issuecomment-1655694291

@tom-sherman Do you know any updates?
I guess it's unlikely that the React docs specify such details.

**Comment by tylerlaws0n** [comment]
> Explore Jotai integration

@dai-shi Is this still something that needs exploration? 

If yes, what are some things that you'd be concerned about with using jotai + waku?

I suspect some exploration has been done already though, considering the waku.gg docs use example code with jotai as the state library.

**Comment by dai-shi** [comment]
> I suspect some exploration has been done already though, considering the waku.gg docs use example code with jotai as the state library.

The example in docs is what's possible now. What I would like to explore is to use atoms on the server too (that is connected to the client behind the scenes.) So, it's a very tight integration (and one reason that I started developing my own framework.)

I have a goal but don't have the implementation idea yet. #11 is an old attempt.

Anyway, there are so many things to do before working on it.

**Comment by sarat1669** [comment]
@dai-shi does https://github.com/nksaraf/vinxi help with this roadmap?

**Comment by dai-shi** [comment]
I don't believe so. Waku's design conflicts with Vinxi's design. So, it's unlikely that we use it at any time soon. We don't know the far future. Related discussion: #522

**Comment by rmarscher** [comment]
Maybe "react compiler" should be added to the roadmap? https://github.com/dai-shi/waku/pull/857#discussion_r1737594978

**Comment by newsve** [comment]
FWIW, server functions != server actions (since these terms were used interchangeably in this thread).

Server functions are much broader and flexible while server actions have a specific use case (form submission/data mutation). Server functions are essential for any new framework and should be the focus in my view. Server actions in contrast, have more restrictions, e.g., are limited to one "client page" (in Next and in SvelteKit too) and lack many features you would get with your custom form submission logic. Server actions will still have there place, question is how often APIs and implementations will change till they are on par with a custom implementation.

**Comment by newsve** [comment]
Re jotai: Big fan of jotai and btw, valtio too.  I am not sure if state management should be integrated. While it is great to have all batteries-included and people still can use any other state management library next to jotai, there is still some subtle issue:

If jotai upgrades its major version some time in the future and waku migrates to that new major version too, everybody who wants to upgrade waku is forced to upgrade jotai too (and refactor jotai-related code). However, I do not think that jotai will ever change significantly but you never know. 

Not too sound to abstract: Svelte did exactly this. While the integration of their state management with the rest of their framework is absolutely amazing, users are forced some time in the future to move completely to their new state management (Runes), the old system is still supported but it is announced that it is going away from version 6 or 7.

For state-heavy code-bases this means a huge refactor and we are thinking about to migrate the code back React (with LLMs) which is faster than rewriting it with Svelte's new state management system.

Again, I do not think that jotai will ever be refactored like Svelte has been but just wanted to share my experiences (so feel free to ignore) and besides, the reason why I check out the state of React frameworks and in particular waku which has already been doing a lot of right architectural design choices.

**Comment by dai-shi** [comment]
If you were to use jotai and other state management libs for client state, nothing would change. My Jotai integration exploration is basically an opt-in feature. Just like RSC is opt-in to client-only React.

**Comment by rmarscher** [comment]
> FWIW, server functions != server actions (since these terms were used interchangeably in this thread).

See the note at https://react.dev/reference/rsc/server-functions

> Until September 2024, we referred to all Server Functions as “Server Actions”.

The Waku blog post announcing Server Actions happened right before React decided to change the term. https://waku.gg/blog/server-actions-are-here

**Comment by dai-shi** [comment]
just fyi: https://x.com/dai_shi/status/1840947256264180130

**Comment by nyomansunima** [comment]
You're doing a great jobs. Love it. Simplicity is must.

👍 💯

**Comment by fuma-nama** [comment]
curious why not making middleware a part of router API like `createMiddleware(...)` in `createPages()`, and add more features & independent type to Waku middlewares, like additional option to only execute during build/static generation by hooking on https://github.com/wakujs/waku/blob/aa775fd02f11b28ce9896a8710bc86d429494488/packages/waku/src/lib/vite-rsc/handler.ts#L144 (impossible to hook atm) and only on request time (currently supported via `middlewareFns`).

**Comment by dai-shi** [comment]
Would you mind opening a new discussion? (and let's not call it "middleware".) please provide use cases.

**Comment by fuma-nama** [comment]
I see, I wrote my idea in #2094, would like to hear some inputs from you

**Comment by fuma-nama** [comment]
Curious will v1 or future versions use `vite.config.ts` instead of `waku.config.ts`? Seems common in other frameworks like tanstack start, I think it would be cool if configurations for framework & vite can be unified into `vite.config.ts`.

**Comment by dai-shi** [comment]
Would you mind opening a new discussion? No such plan currently, but open to hear use cases.

**Comment by fuma-nama** [comment]
done https://github.com/wakujs/waku/discussions/2269, tho it's just an idea about the API design rather than actual use case, not sure if you'll be interested in this direction
